# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

target "manvsmagic" do
    pod 'MWFeedParser'
    pod 'SVProgressHUD'
end

target "manvsmagicTests" do

end

